### PR TITLE
Added BE (belgian french) keyboard layout for badusb

### PR DESCRIPTION
**Pull request by Bramard**
# What's new

- Added BE keyboard layout for Badusb

# Verification 

- compile & flash from file with qflipper

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

### CODE REVIEW

**Comment by v1nc** [comment]
Thanks for your contribution, I merged the commit and will release the updated firmware soon.

**Comment by Bramard** [comment]
Thank you, I'll compile right away :)

**Comment by v1nc** [comment]
>Thank you, I'll compile right away :)

You are welcome, please fetch the latest changes before compiling.
Please also make a PR at the unleashed repo :)

**Comment by Bramard** [comment]
@v1nc done ;)

**Pull request merged**
